version: "3.9"

services:
  iframe-chat:
    image: node:20
    container_name: iframe-chat
    restart: unless-stopped
    working_dir: usr/src/app
    command: sh -c "npm install && node server.js"
    ports:
      - "3001:3000"  # 對外端口
    volumes:
      - ./app:/usr/src/app
      - ./app/chats:/usr/src/app/chats       # 對話資料持久化
      - ./app/default:/usr/src/app/default   # CSS/JS 預設檔
